### ISSUE TITLE
place button in navbar not working

### ISSUE THREAD

**Issue by kumar1397** [Omkar-Sonawane-23/Tourism#10]
**Describe the bug**
The place button in the navbar is desired to take the user to the content page but it is not working. 

**To Reproduce**
1. Go to  https://tourism-peach.vercel.app/
2. Click on places button at navbar
3. See error

**Expected behavior**
upon clicking on the button, it should take the user to the content page with different tourism places.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Microsoft edge

**Additional context**
Hey @Omkar-Sonawane-23 ,
I can work on this issue. please assign this to me under GSSoC '24

**Comment by Omkar-Sonawane-23** [comment]
another person is already working on this 
Issue : #9
