### ISSUE TITLE
To add images and fix image related bugs.

### ISSUE THREAD

**Issue by Shivangi015** [Omkar-Sonawane-23/Tourism#101]
In places section of the project some images are not present, these images have to be added. 
And the image which are added are not related to the place, which should be changed, also some images are ruined because they does not fit in the size provided for them.
![image](https://github.com/Omkar-Sonawane-23/Tourism/assets/115791035/3730036f-3d6d-4958-9acc-028c9472fdce)
![image](https://github.com/Omkar-Sonawane-23/Tourism/assets/115791035/bdbd8401-8d75-4292-9040-0ed965d5ef46)
I can fix all images related bugs and also can style this section to make them more appealing.

**Comment by Shivangi015** [comment]
Also the text and font style are not good, the text are really hard to read due to the color chosen for the font. I can fix the issue related to font. @Omkar-Sonawane-23 please assign this task to me.

**Comment by jinamsancheti** [comment]
I would like to work on this issue. @Omkar-Sonawane-23  can you please assign it to me under GSSOC'24?
