### ISSUE TITLE
Imporve design for Details.jsx

### ISSUE THREAD

**Issue by Faraaz22** [Omkar-Sonawane-23/Tourism#102]
Improper alignment of the Details section as well as poor design

I would like to align it so it looks more centralized and make the design more pleasing to the eye.

<img width="949" alt="image" src="https://github.com/Omkar-Sonawane-23/Tourism/assets/130041060/13a2d70c-4113-401d-900b-2629f4774de8">

Kindly assign this to me under Gssoc'24.

**Comment by Omkar-Sonawane-23** [comment]
Duplicate
