### ISSUE TITLE
Dark mode and light mode feature

### ISSUE THREAD

**Issue by AyushShukla3466** [Omkar-Sonawane-23/Tourism#108]
Light mode and dark mode are important because they offer users flexibility and customization in their viewing experience, catering to different preferences, reducing eye strain, and enhancing readability in various lighting conditions.

**Comment by Syed0206** [comment]
I would like to work on this issue @Omkar-Sonawane-23 can you please assign me this under GSSOC'24

**Comment by Omkar-Sonawane-23** [comment]
Duplicate
