### ISSUE TITLE
Many Issues

### ISSUE THREAD

**Issue by Rajput-xv** [Omkar-Sonawane-23/Tourism#113]
Problems I would like to rectify :-

1. while navigation to places from home page the route is different then it should be.
2. add links to logo and other items in navbar as it is not redirecting to any page.
3. add some indicator in navbar so that the current page will be easily identified.
4. add footer for website.
5. Improve the card section in specific explore page of places.
6. fix layout of places page.
7. images not displayed in places page and in their specific explore page also.
8. Add full About Us page.

Hey @Omkar-Sonawane-23 ,
I would like to resolve all these issues, if You would like to assign this to me, kindly do.

**Comment by Omkar-Sonawane-23** [comment]
Some of them are solved

**Comment by Rajput-xv** [comment]
> Some of them are solved

kindly let me know which are left, i can work on them!

**Comment by bhavanamn** [comment]
Yes please do let me know which are left , i can work on them

**Comment by Omkar-Sonawane-23** [comment]
Check Dev Branch
