### ISSUE TITLE
Replacing the favicon icon and title of Vite+react  from the website.

### ISSUE THREAD

**Issue by KARANSINGH34951** [Omkar-Sonawane-23/Tourism#117]
I have noticed that there is still vite+react favicon and title on the website. I can replace it with a logo and your website name. 

1. Simply go to the website and you able to see it.

**Screenshots**
![favicon](https://github.com/Omkar-Sonawane-23/Tourism/assets/137412876/d4fa3c20-f5b9-498c-ab08-98fad312aeca)

Assign me this issue under GSSOC 2024.

**Comment by Omkar-Sonawane-23** [comment]
Duplicate
