### ISSUE TITLE
Adding Contact Us page and Footer

### ISSUE THREAD

**Issue by gupta-ritik** [Omkar-Sonawane-23/Tourism#118]
**Importance of Contact Us page** 
The "Contact Us" page on a website is a pivotal element that bridges the gap between site visitors and the website owner or organization. It serves as a central hub for inquiries, feedback, and communication, bolstering trust and credibility by offering a direct line of contact. Beyond mere accessibility, it functions as a conduit for customer support, lead generation, and feedback collection, nurturing relationships with users. By providing multiple contact options such as forms, email addresses, phone numbers, and physical addresses, it caters to diverse user preferences and ensures accessibility. A well-crafted Contact Us page not only enhances the overall user experience but also demonstrates a commitment to transparency and responsiveness. It can also aid in legal compliance by providing necessary information mandated by regulations. In essence, the Contact Us page is indispensable, fostering engagement, trust, and communication between a website and its audience

**Importance of Footer** 
The footer of a website plays a critical role in enhancing user experience and website functionality. It provides vital information such as contact details, social media links, and navigational shortcuts, aiding user navigation and accessibility. Additionally, it reinforces brand identity and credibility by displaying copyright information, privacy policies, and terms of service. The footer often houses essential links like sitemaps, helping users discover content efficiently. Furthermore, it improves SEO by including internal links and reinforcing site structure. In essence, the footer serves as the foundation that anchors user interaction, reinforces brand trust, and optimizes website performance.

please ASSIGN is to me for resolving the problem

**Comment by Omkar-Sonawane-23** [comment]
Duplicate
