### ISSUE TITLE
Page Reloading Error

### ISSUE THREAD

**Issue by Mayur-666** [Omkar-Sonawane-23/Tourism#126]
**Describe the bug**
On clicking navbar links like "Places" and "About us" the page gets reload, which is very bad for react as it offers single page websites.

**To Reproduce**
Steps To Reproduce this Behavior :- 
1. Go to 'Home page.'
2. Click on Places in navbar
3. See page reload

**Expected behavior**
The links in navbar should redirect to respective pages without reloading the page.

**Screenshots**
We can see the page is reloading when i clicked the places button in navbar.
![Screenshot (518)](https://github.com/Omkar-Sonawane-23/Tourism/assets/118804110/8da20232-441f-4514-a813-a66ad8d67a2a)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser : chrome, edge, firefox, brave
 - 
**Smartphone (please complete the following information):**
 - Device: Realme
 - OS: Android
 - Browser Brave, Chrome, Internet Explorer

**Comment by Mayur-666** [comment]
Please assign me this issue.

**Comment by AdityaChaudhari03** [comment]
Could you please assign me to this issue?

**Comment by Vaibhavtech2006** [comment]
1. Identified the trigger for page reloads.
2. Reviewed browser console for errors and warnings.
3. Inspected network activity for failed requests.
4. Debugged state changes in components.
5. Checked route configurations in React Router.
6. Tested in different environments to isolate the issue.
7. Updated dependencies to the latest versions.
8. Disabled browser extensions that might interfere.
9. Implemented error boundaries to handle errors gracefully.
10. Sought help from online communities for further assistance.

**Comment by Mayur-666** [comment]
But this issue is not completed, the problem still persist in production
@Omkar-Sonawane-23

**Comment by Omkar-Sonawane-23** [comment]
Fixed in dev branch
