### ISSUE TITLE
Lacks dark mode and light mode toggle feature

### ISSUE THREAD

**Issue by Codemaster019** [Omkar-Sonawane-23/Tourism#128]
Feature Request: Dark Mode and Light Mode Toggle switch

Description:
Currently, the application lacks the flexibility of adjusting its interface according to user preferences for light or dark mode. As more users are becoming accustomed to interfaces that offer both modes, it's essential to provide this feature for a better user experience and accessibility.

Proposal:
Integrate a **toggle switch** in the application settings or somewhere easily accessible within the interface to allow users to switch between dark mode and light mode seamlessly. This toggle should persist across sessions, remembering the user's preference for subsequent visits.

Benefits:
1. User Preference: Enables users to choose their preferred mode, enhancing comfort and reducing eye strain, particularly in low-light environments.
2. Accessibility: Improves accessibility for users with visual impairments by offering a high-contrast option.
3. Enhanced Experience: Provides a more personalized experience, catering to diverse user preferences.

We believe that implementing this feature will significantly enhance the usability and appeal of our application. Looking forward to your feedback and considering this request for future development efforts.

**Comment by Omkar-Sonawane-23** [comment]
Duplicate
