### ISSUE TITLE
Fix the about us page's broken link

### ISSUE THREAD

**Issue by Hrishita-Paul** [Omkar-Sonawane-23/Tourism#133]
**Describe the bug**
Broken link of about us page.

**To Reproduce**
1. Go to navbar.
2. Click on about us.
3. See error

**Expected behavior**
On clicking the about us on navbar, it redirects to the places page.

**Screenshots**

**Desktop **
 - OS: [e.g. Windows]
 - Browser [e.g. chrome, ]

**Comment by Hrishita-Paul** [comment]
@Omkar-Sonawane-23 please assign the GSSoC and level labels and assign this issue to me.
I will create a new about us page to represent the facilities provided by the site and leaving reviews for the site by the visitors.

**Comment by bilalshaikh292** [comment]
@Hrishita-Paul there is already a PR being created.

**Comment by Omkar-Sonawane-23** [comment]
Duplicate.
