### ISSUE TITLE
Add a footer to the website

### ISSUE THREAD

**Issue by komal-agarwal5** [Omkar-Sonawane-23/Tourism#139]
**Is your feature request related to a problem? Please describe.**
I wish to add a footer to the website 

**Describe the solution you'd like**
The footer will contain hyperlinks to the home about and places page and the copyright and made by information to be displayed there.

**Describe alternatives you've considered**
NA

**Additional context**
NA

**Comment by riteshpushkar** [comment]
I can add this footer pls assign me this issue under GSSoC24, Thank you

**Comment by Omkar-Sonawane-23** [comment]
Duplicate.
