### ISSUE TITLE
Favicon is not set .

### ISSUE THREAD

**Issue by PratikMane0112** [Omkar-Sonawane-23/Tourism#140]
**Describe the bug**
Favicon is missing for website .

**Screenshots**
![Screenshot 2024-05-12 195149](https://github.com/Omkar-Sonawane-23/Tourism/assets/153143167/2ef4a58e-9c27-400f-aa84-be10e83bded4)

**To Reproduce**
I will add a appropriate favicon for all the pages which would match with website.

**Expected behavior**
Looks good and website will have its own identity

**Comment by Omkar-Sonawane-23** [comment]
Duplicate
