### ISSUE TITLE
Add icons on the navbar

### ISSUE THREAD

**Issue by harshmishra19** [Omkar-Sonawane-23/Tourism#155]
**Is your feature request related to a problem? Please describe.**

The current navbar lacks icons, which impacts its visual appeal and usability. Users might find it less engaging and intuitive to navigate through the website without visual cues provided by icons.

**Describe the solution you'd like**

I propose adding respective icons to the navbar to enhance its visual appeal and improve user navigation experience. These icons will align with the theme of the website and provide users with clear visual cues for each navigation option

**Describe alternatives you've considered**

One alternative could be redesigning the navbar layout or color scheme. However, adding icons is a more direct and effective solution to address the visual appeal and usability concerns of the navbar

**Additional context**

![Screenshot 2024-05-11 080754](https://github.com/Omkar-Sonawane-23/Tourism/assets/115486960/a239705a-6f6d-4c85-93ef-e4af470c2a86)
![Screenshot 2024-05-12 083752](https://github.com/Omkar-Sonawane-23/Tourism/assets/115486960/934be1a8-35a0-40e3-a789-dbd380a3aacb)

Could you plz assign this issue to me under GSSOC24

**Comment by Shravani246** [comment]
@harshmishra19 I can complete it.Please assign this issue.
