### ISSUE TITLE
Update Readme file

### ISSUE THREAD

**Issue by harshmishra19** [Omkar-Sonawane-23/Tourism#156]
**Is your feature request related to a problem? Please describe.**

In your current readme file there is no instruction for the beginners on how they can contribute to the project 

**Describe the solution you'd like**

I would like to update the readme and want to make it more beginner-friendly 

**Describe alternatives you've considered**

**Additional context**

![Screenshot 2024-05-13 093400](https://github.com/Omkar-Sonawane-23/Tourism/assets/115486960/8209044f-ccca-4a98-b067-4e81dc989404)

Can you plz assign

**Comment by d1vyadharsh1n1** [comment]
Hi @Omkar-Sonawane-23. I would like to update the readme file by adding screenshots of the project. I would also like to make the readme file more precise and beginner friendly. Can you assign it to me

**Comment by Omkar-Sonawane-23** [comment]
Duplicate
