### ISSUE TITLE
Improvement of Navbar UI

### ISSUE THREAD

**Issue by AlaynaShaheen** [Omkar-Sonawane-23/Tourism#16]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by AlaynaShaheen** [comment]
I am a contributor at GSSoC'24. I found that the navbar spacing isn't visually appealing. I can solve this issue by giving correct spacing in navbar. Please assign this issue to me.

**Comment by sarthak-stranger** [comment]
hi, Can you please assign this issue to me, i have so experience in designing so i have seen that margin  is not properly in our nav bar section and also i will improve the UI of navbar
![Screenshot (208)](https://github.com/Omkar-Sonawane-23/Tourism/assets/92575432/80808a3d-3999-4e9f-aad1-d5b1138ead30)

**Comment by nishant0708** [comment]
hey @AlaynaShaheen  i can fix this issue please assign it to me

**Comment by Omkar-Sonawane-23** [comment]
@sarthak-stranger You can start work on this.

**Comment by sarthak-stranger** [comment]
Thank you for assigning this issue.@Omkar-Sonawane-23

**Comment by sarthak-stranger** [comment]
@Omkar-Sonawane-23 Can you please give me your discord id or something else , to discuss more about work.

**Comment by Omkar-Sonawane-23** [comment]
@sarthak-stranger you can join discord channel. link is in readme file.

**Comment by khushikunte** [comment]
I am khushi kunte.I would like to work on this issues.Please assign this task to me.

**Comment by sarthak-stranger** [comment]
@Omkar-Sonawane-23 Check  PR, if it is Ok then please merge it.
