### ISSUE TITLE
Adding favicon

### ISSUE THREAD

**Issue by Khanishsuresh** [Omkar-Sonawane-23/Tourism#160]
By creating a good icon for the project and adding to your project

I would like to create an icon for your project and adding it as the favicon to your project

**Comment by Khanishsuresh** [comment]
Hi @Omkar-Sonawane-23 ,

As a GSSOC'24 contributor, I would like to contribute a logo to your project
Would you please assign me to this issue under GSSOC'24 .

**Comment by Omkar-Sonawane-23** [comment]
duplicate.
