### ISSUE TITLE
Adding attractive UI for the places

### ISSUE THREAD

**Issue by Khanishsuresh** [Omkar-Sonawane-23/Tourism#161]
![image](https://github.com/Omkar-Sonawane-23/Tourism/assets/136162512/d022fe3b-4d84-4e15-82ac-85c9800693e5)

Making the places container more attractive and responsive for the user
Making changes to the container would make the UI more user-friendly to explore the places

**Comment by Khanishsuresh** [comment]
Hii @Omkar-Sonawane-23 ,

I would like to contribute to your project 
would u please assign me under GSSOC'24

**Comment by Khanishsuresh** [comment]
Hii @Omkar-Sonawane-23 ,

I would like to contribute to your project 
would u please assign me under GSSOC'24

**Comment by Abhishek0732** [comment]
@Khanishsuresh I want to add another card in the places section with responsive page assign it to me under gssoc24

**Comment by Omkar-Sonawane-23** [comment]
Duplicate.
