### ISSUE TITLE
Issue with places Link Functionality Discrepancy

### ISSUE THREAD

**Issue by vinay02103** [Omkar-Sonawane-23/Tourism#165]
@Omkar-Sonawane-23 I would like to work on this issue

Description:
I've encountered an inconsistency in the functionality of links within the application. Specifically, while one link directs users to the intended destination without any issues, another link seems to be malfunctioning, failing to navigate users to the expected location.
![Screenshot 2024-05-13 145722](https://github.com/Omkar-Sonawane-23/Tourism/assets/140578491/708ad415-1cf0-49f6-9694-bf6060389f10)
![Screenshot 2024-05-13 145623](https://github.com/Omkar-Sonawane-23/Tourism/assets/140578491/f33f656e-aecd-4cf0-b97e-7d659177d9ca)

Steps to Reproduce:
1.Navigate to [Places].
2.Click on the link labeled [Places] - observe successful redirection.
3.Navigate to [Places].
4.Attempt to click on the link labeled [Places] - note the failure to redirect.
Expected Behavior:
Both links should navigate users to the respective destinations consistently.

**Comment by riteshpushkar** [comment]
Pls assign me this issue I would love to solve it. Thank You Omkar.

**Comment by Omkar-Sonawane-23** [comment]
Duplicate.
