### ISSUE TITLE
Adding a scroll to top button

### ISSUE THREAD

**Issue by pani2004** [Omkar-Sonawane-23/Tourism#172]
I can add a scroll to top button to the /home page.
![Screenshot (27)](https://github.com/Omkar-Sonawane-23/Tourism/assets/154724111/b00204e3-bbba-4d4e-ba67-d5a023bc1638)

**Comment by pani2004** [comment]
@Omkar-Sonawane-23 I can work on this can u please assign this to me?

**Comment by anshdeep0504** [comment]
Hey, allow me to work on this under GSSOC' 2024

**Comment by Gokul-ram-j** [comment]
@Omkar-Sonawane-23  assign me this issue

**Comment by pani2004** [comment]
@Omkar-Sonawane-23 Please review this PR https://github.com/Omkar-Sonawane-23/Tourism/pull/252#issue-2301102688

**Comment by pani2004** [comment]
@Omkar-Sonawane-23  @sameer-soni  Please review this PR. https://github.com/Omkar-Sonawane-23/Tourism/pull/253#issue-2301151282
