### ISSUE TITLE
Improve the Hover Effect on each card in Places section

### ISSUE THREAD

**Issue by priyankaa-2004** [Omkar-Sonawane-23/Tourism#181]
**Describe the bug**
The description on the places cards are on the picture which hampers the user experience and also the description is getting overlapped somewhere or the other.

**Expected behavior**
When the user will hover over the card, its description and explore more option will appear which will help the website look clean and more user friendly.

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: chrome

**Smartphone (please complete the following information):**
 - Device: Samsung M42
 - OS: Android
 - Browser Chrome

**Additional context**
Assign this issue to me @Omkar-Sonawane-23

**Comment by Mehulsingh1010** [comment]
assign me this task i want to contribute here
