### ISSUE TITLE
Fix the broken links of some cards & also add more famous travel destinations

### ISSUE THREAD

**Issue by ArjunParajuli** [Omkar-Sonawane-23/Tourism#186]
**Describe the bug**
Images on some cards are not shown and also their respective explore pages don't show images.

**To Reproduce**
1. Go to Navbar
2. Click on Places
3. Scroll down, some cards are not showing images 

**Expected behavior**
Fix the images for some places which are not showing currently and also add some more captivating destinations. 

**Screenshots**
![Screenshot 2024-05-13 162714](https://github.com/Omkar-Sonawane-23/Tourism/assets/104476004/6865a128-551a-48f6-a078-2eada8c8bd38)

@Omkar-Sonawane-23  Kindly assign me this task under GSSOC'24

**Comment by ArjunParajuli** [comment]
URL of my PR:  https://github.com/Omkar-Sonawane-23/Tourism/pull/205

Please approve!

**Comment by sameer-soni** [comment]
fixed in #164
