### ISSUE TITLE
Explore page not working

### ISSUE THREAD

**Issue by yugal1107** [Omkar-Sonawane-23/Tourism#218]
Explore page is not working due to incorrect code in explore.jsx file and explore button is also not working.

I will improve explore page by correcting its jsx file.

![image](https://github.com/Omkar-Sonawane-23/Tourism/assets/119532503/376a33fc-c087-4f3f-b4c9-e0195802e5ce)

**Comment by yugal1107** [comment]
Please assign this issue to me and add gssoc label.

**Comment by anshdeep0504** [comment]
Hey, allow me to work on this under GSSOC' 2024

**Comment by yugal1107** [comment]
Please assign this issue to me , I can make a good and attractive explore page under GSSOC .
Thank you

**Comment by mtg718** [comment]
Hi @sameer-soni , please assign this issue to me under GSSoc'24
