### ISSUE TITLE
Fixing broken links

### ISSUE THREAD

**Issue by YadlaMani** [Omkar-Sonawane-23/Tourism#221]
**Describe the bug**
Some places have images that are not displaying due to broken links. 

**To Reproduce**
1.Visit the website home page

**Screenshots**
Some places have images that are not displaying due to broken links.
![image](https://github.com/Omkar-Sonawane-23/Tourism/assets/133841094/cddc6d97-e2f8-4f36-a9af-642ee80575f0)

**Comment by YadlaMani** [comment]
@Omkar-Sonawane-23  assing me this issue under gssoc 2024

**Comment by sameer-soni** [comment]
fixed
