### ISSUE TITLE
Adding Responsive About us page

### ISSUE THREAD

**Issue by yashwagh30** [Omkar-Sonawane-23/Tourism#225]
![Screenshot 2024-05-15 172731](https://github.com/Omkar-Sonawane-23/Tourism/assets/120586606/9239a048-690e-46d0-852b-4749fa318c74)
![Screenshot 2024-05-15 172745](https://github.com/Omkar-Sonawane-23/Tourism/assets/120586606/2dbeb2a5-023f-4f7f-bfe0-f28c702f9355)

Will add a following alook like about us to the given website. And can add more styling if required. Can you please assign me this issue under label gssoc and level1.
Thank you

**Comment by Gokul-ram-j** [comment]
please assign me this issue @yashwagh30

**Comment by sameer-soni** [comment]
#236
