### ISSUE TITLE
Website is not responsive

### ISSUE THREAD

**Issue by suraj-9849** [Omkar-Sonawane-23/Tourism#23]
**Is your feature request related to a problem? Please describe.**
![image](https://github.com/Omkar-Sonawane-23/Tourism/assets/146669517/fb52152d-be24-4216-8c47-76ea3759dc55)
As you can see the webpage is getting messed up when we view it in the mobile mode

**Describe the solution you'd like**
I will be following the tailwind and make it responsive
So I would like to work on this issue. So please assign me. @GSSOC'24 @Omkar-Sonawane-23

**Comment by Omkar-Sonawane-23** [comment]
@suraj-9849 You can start working on this.

**Comment by suraj-9849** [comment]
https://github.com/Omkar-Sonawane-23/Tourism/assets/146669517/aeb46458-381c-41af-a410-1445fe1450b3

is this ok @Omkar-Sonawane-23  or am I suppose to make more changes. I added the responsive ness in both the Navbar and Homequeue also changed the cards

**Comment by suraj-9849** [comment]
https://github.com/Omkar-Sonawane-23/Tourism/assets/146669517/dc1b566d-34c8-4a70-9320-9e097ceb8ccd

and this is the change in the cards

**Comment by suraj-9849** [comment]
if this is ok then I will create a PR

**Comment by Omkar-Sonawane-23** [comment]
You Done a Great Job Just Change The Nav Elements Structure, like Onclicking Only Nav Elements has To pop up But In This Case Whole Navbars Height is Changed.

**Comment by suraj-9849** [comment]
Ok I will make it

**Comment by suraj-9849** [comment]
@Omkar-Sonawane-23 can u please tell me the issue I will try to sort it out please.

https://github.com/Omkar-Sonawane-23/Tourism/assets/146669517/7a0e0ce4-f266-4b63-affd-fc825b1fca96

Everything is working perfectly right then what happen
