### ISSUE TITLE
Design About Us Page

### ISSUE THREAD

**Issue by Hemashree21** [Omkar-Sonawane-23/Tourism#236]
The About Us link in the navbar is not redirecting to any other page and I want to work on it.

![Screenshot 2024-05-12 091913](https://github.com/Omkar-Sonawane-23/Tourism/assets/138188163/84509aa0-e533-4d7a-8a43-08ffcaa716ef)

![Screenshot 2024-05-13 180820](https://github.com/Omkar-Sonawane-23/Tourism/assets/138188163/2c4a8744-3aad-4c53-8095-f6b9d611976e)

These are some of the templates I previously worked on and I'll change the theme according to the current requirements.

Please assign this issue to me.

**Comment by sameer-soni** [comment]
@Hemashree21 okay, assigning this to you.

**Comment by mtg718** [comment]
Hi @Omkar-Sonawane-23 , please assign this issue to me under GSSoc'24

**Comment by Hemashree21** [comment]
@sameer-soni can you please send the discord invite link? The one in Readme file is expired

**Comment by sameer-soni** [comment]
@Hemashree21 [discord link](https://discord.gg/Pfp5CS4cNr)
