### ISSUE TITLE
Contact us styling

### ISSUE THREAD

**Issue by anshulsoni4** [Omkar-Sonawane-23/Tourism#246]
**Is your feature request related to a problem? Please describe.**
Contact us page is not styled like the design of page

**Comment by vanamuthuV** [comment]
please assign this issue to me under GSSOC'24

**Comment by sameer-soni** [comment]
@vanamuthuV okay, there is not contact us page, assigning this issue to you.

**Comment by vanamuthuV** [comment]
@sameer-soni  to reconfirm again as you mentioned it's a page(contact us page), i need to provide a separate "route (/contactus)" and i should update the contact us label in header, Right??

**Comment by anshulsoni4** [comment]
> @vanamuthuV okay, there is not contact us page, assigning this issue to you.

i think i opened this issue??

**Comment by vanamuthuV** [comment]
@anshulsoni4  but i got assigned, should i back ?

**Comment by anshulsoni4** [comment]
> @anshulsoni4 but i got assigned, should i back ?

yes

**Comment by vanamuthuV** [comment]
@sameer-soni , what's the decision, should i left assigned (I'm completely interested) or assign to @anshulsoni4

**Comment by anshulsoni4** [comment]
> @sameer-soni , what's the decision, should i left assigned (I'm completely interested) or assign to @anshulsoni4

well, you're interested in the topic that i gave, so :)

**Comment by vanamuthuV** [comment]
> > @sameer-soni , what's the decision, should i left assigned (I'm completely interested) or assign to @anshulsoni4
> 
> well, you're interested in the topic that i gave, so :)

So, let's wait for @sameer-soni decision 🙂

**Comment by sameer-soni** [comment]
@anshulsoni4 yes you opened this issue but you didn't mention that you want to work on this. I've already assigned vanamuthuV to this, you select any other issue and I'll assign you there.

**Comment by anshulsoni4** [comment]
> @anshulsoni4 yes you opened this issue but you didn't mention that you want to work on this. I've already assigned vanamuthuV to this, you select any other issue and I'll assign you there.

alright then

**Comment by vanamuthuV** [comment]
> @anshulsoni4 yes you opened this issue but you didn't mention that you want to work on this. I've already assigned vanamuthuV to this, you select any other issue and I'll assign you there. 

Thanks for the confirmation 🙂, and a small query that I should open up a separate route for contact us or fix it in the  bottom of the landing page, how you need ?

**Comment by sameer-soni** [comment]
> > @anshulsoni4 yes you opened this issue but you didn't mention that you want to work on this. I've already assigned vanamuthuV to this, you select any other issue and I'll assign you there.
> 
> alright then

@anshulsoni4  Hey, how will I know if you want to work on a particular issue unless you will tell, I had already assigned him and it doesn't feel right to remove him. Sorry man but try to understand.

**Comment by sameer-soni** [comment]
> > @anshulsoni4 yes you opened this issue but you didn't mention that you want to work on this. I've already assigned vanamuthuV to this, you select any other issue and I'll assign you there.
> 
> Thanks for the confirmation 🙂, and a small query that I should open up a separate route for contact us or fix it in the bottom of the landing page, how you need ?

@vanamuthuV A separate page would be nice.

**Comment by vanamuthuV** [comment]
> > > @anshulsoni4 yes you opened this issue but you didn't mention that you want to work on this. I've already assigned vanamuthuV to this, you select any other issue and I'll assign you there.
> > 
> > 
> > Thanks for the confirmation 🙂, and a small query that I should open up a separate route for contact us or fix it in the bottom of the landing page, how you need ?
> 
> @vanamuthuV A separate page would be nice.

Gotcha!!
