### ISSUE TITLE
Add more cities to the places

### ISSUE THREAD

**Issue by anshulsoni4** [Omkar-Sonawane-23/Tourism#248]

**Comment by mtg718** [comment]
Hi @Omkar-Sonawane-23 , please assign this issue to me under GSSoc'24

**Comment by anshulsoni4** [comment]
@sameer-soni assign here also 
THanks

**Comment by sameer-soni** [comment]
@mtg718  assigning you to this issue.

**Comment by mtg718** [comment]
ok @sameer-soni , I will add more cities

**Comment by mtg718** [comment]
Hello, @sameer-soni , I had raised a pull request (mohit_addingCities- branch) please verify and merge it, thanks
