### ISSUE TITLE
Create Hover effect on places for each Card

### ISSUE THREAD

**Issue by ayushnandi** [Omkar-Sonawane-23/Tourism#249]
### Issue
I propose adding hover effects to each card in the "Places" section to enhance interactivity and user-friendliness.

### Proposed Enhancement:
![image](https://github.com/Omkar-Sonawane-23/Tourism/assets/110190468/437f57f7-b76a-4353-bffa-9f152c15fcc2)

 
Adding hover effects to the cards in the "Places" section will make the page more interactive and engaging for users. When users hover over a card, it should respond with a visually appealing effect, such as a subtle animation or color change, providing feedback and enhancing the overall user experience.

### Expected Outcome
Implementing hover effects on the cards in the "Places" section will improve user engagement and make the page more dynamic. This enhancement aligns with our goal of creating a user-friendly and visually appealing website.

### Additional Details
- I will ensure that the hover effects are consistent with the design language of the website and do not compromise the overall aesthetics.
- This enhancement will require modifications to the existing CSS code for the "Places" section.
- I am open to collaborating with other contributors to brainstorm and implement creative hover effects that enhance user interaction.

Kindly assign this issue to me under GSSoC 24.

**Comment by sameer-soni** [comment]
okay @ayushnandi , make it look good.

**Comment by namandude** [comment]
Hey  @sameer-soni  @ayushnandi  !! 
I would like to help you in it . We will make it look more appealing and engaging . 
Thank You!

**Comment by anuukriti** [comment]
Hey @sameer-soni @ayushnandi 
I would like to work on this project. Please assign me.
Thank You!

**Comment by mtg718** [comment]
Hi @Omkar-Sonawane-23 , please assign this issue to me under GSSoc'24
