### ISSUE TITLE
[FIX] Changing the title of the project!

### ISSUE THREAD

**Issue by chaitanyarora** [Omkar-Sonawane-23/Tourism#25]
Currently the title of the project is Vite+React, I'll change it to Bharat Yatra, with an icon.

**Comment by GarimaSingh0109** [comment]
i am willing take this task  i will replace it with a creative and unique logo. kindly assign me this task under #gssoc'24

**Comment by Kk015** [comment]
Please assign me this task with the #gssoc'24. Thank you.

**Comment by chaitanyarora** [comment]
@Omkar-Sonawane-23 Sir I have resolved this issue in my latest PR!

**Comment by Omkar-Sonawane-23** [comment]
Duplicate
