### ISSUE TITLE
Add Footer

### ISSUE THREAD

**Issue by teamharsh** [Omkar-Sonawane-23/Tourism#26]
by add footer web page look good

**Comment by cpratik1307** [comment]
I am thrilled to be participating in GirlScript Summer of Code 2k24 as a passionate computer science student with a keen interest in web development. I am eager to contribute to your project and leverage my skills to make meaningful contributions. I look forward to collaborating with you and the team to create impactful solutions.

**Comment by GarimaSingh0109** [comment]
i am willing to add footer to the page please assign me this task under #gsssoc'24

**Comment by Omkar-Sonawane-23** [comment]
No Need To Add Footer
