### ISSUE TITLE
Adding Travel Tips as it is empty

### ISSUE THREAD

**Issue by somilyadav7** [Omkar-Sonawane-23/Tourism#270]
Adding Travel Tips as it is empty in all the places or making it visible 
![Screenshot 2024-05-17 145656](https://github.com/Omkar-Sonawane-23/Tourism/assets/95069908/240305d6-6130-4026-98de-0df5ed511029)

**Comment by MckinellGreen7** [comment]
I am interested in this issue. Please assign this issue to me.
