### ISSUE TITLE
[Feat]: Back To Top button on Explore page 

### ISSUE THREAD

**Issue by Arghyadeep09** [Omkar-Sonawane-23/Tourism#271]
**Is your feature request related to a problem? Please describe.**

The absence of a back-to-top button on the website significantly impairs its user-friendliness and navigational convenience, posing a notable problem in terms of user experience

**Describe the solution you'd like**

There should be a back to top button

**Describe alternatives you've considered**
want to add a back to top button on the explore page

**Additional context**
Like this : 
![image](https://github.com/Omkar-Sonawane-23/Tourism/assets/90449806/9a27160f-c790-44bb-b931-e6b38f8c7da0)

**Comment by Arghyadeep09** [comment]
Under GSSOC 24, Please assign the work to me! @Omkar-Sonawane-23

**Comment by sameer-soni** [comment]
@Arghyadeep09 assigned.
