### ISSUE TITLE
The tags can be made to look yellow if selected

### ISSUE THREAD

**Issue by Rakshit-gen** [Omkar-Sonawane-23/Tourism#273]
![image](https://github.com/Omkar-Sonawane-23/Tourism/assets/64471316/1df3c11a-e78a-475d-9504-55fe532c526a)

These pages can be made to set to a different color when clicked or selected

**Additional context**
I am a GSSOC '24 Contributor. Please assign this issue to me.

**Comment by sameer-soni** [comment]
@Rakshit-gen assigning to you
