### ISSUE TITLE
Design UI for Login and Signup Page

### ISSUE THREAD

**Issue by Hemashree21** [Omkar-Sonawane-23/Tourism#278]
@sameer-soni I want to work on designing the user interface for the Register and Login pages. Please assign this issue to me and do let me know if you want to see any samples.

**Comment by sameer-soni** [comment]
@Hemashree21 Can you tell me the use cases of authentication functionality in this website?

**Comment by Hemashree21** [comment]
@sameer-soni I recently came across an issue where you told that a review and comment section for each suggested place would be a great idea so in order for the user to comment, they must be registered right?

**Comment by Hemashree21** [comment]
And maybe in the future you want to upscale the same website to recommend tourism packages or even save the places you want to visit, user authentication will be necessary.

**Comment by sameer-soni** [comment]
> @sameer-soni I recently came across an issue where you told that a review and comment section for each suggested place would be a great idea so in order for the user to comment, they must be registered right?

👍 okay, assigning it to you.
