### ISSUE TITLE
Feature Request for "Contact Us" Feature

### ISSUE THREAD

**Issue by kushalkumar1362** [Omkar-Sonawane-23/Tourism#280]
I'm always frustrated when users struggle to find contact information or when the current contact options are limited, inefficient, or not user-friendly. This can lead to missed communications and frustrated users who are unable to get the support they need.

### Describe the solution you'd like
I would like a comprehensive "Contact Us" feature

**Contact Form:** A simple and intuitive form that allows users to send a message directly from the website.

Fields for Name, Email, Subject, and Message.

My idea is only based on frontend

**Comment by sameer-soni** [comment]
Duplicate  of #246
