### ISSUE TITLE
For some mobile sizes the header is not responsive .

### ISSUE THREAD

**Issue by Ayushmaanagarwal1211** [Omkar-Sonawane-23/Tourism#300]
**Describe the bug**

for screen size below 500 x 695 the header buttons like search places are overflowing and not responsive .
**To Reproduce**
1. Go to website
2. See the website in mobile view
3. See Error

**Expected behavior**

The buttons will be arranged properly

**Screenshots**

![Screenshot 2024-05-18 093027](https://github.com/Omkar-Sonawane-23/Tourism/assets/118350936/d24bd578-3d9a-4d59-b393-5ef0c8442ede)

![Screenshot 2024-05-18 093027](https://github.com/Omkar-Sonawane-23/Tourism/assets/118350936/7d337d73-dd3b-4cb5-9ce4-bd6ca4a0fbeb)

**Comment by sameer-soni** [comment]
@Ayushmaanagarwal1211 do you want to work on this issue?

**Comment by Ayushmaanagarwal1211** [comment]
Yes

**Comment by sameer-soni** [comment]
@Ayushmaanagarwal1211 assigned.

**Comment by Ayushmaanagarwal1211** [comment]
I am working on that
