### ISSUE TITLE
[BUG]: home is showing instead of places in URL of places page

### ISSUE THREAD

**Issue by chandannekya** [Omkar-Sonawane-23/Tourism#320]
**Describe the bug**
The URL for the "places" page incorrectly displays "home" instead of "places," which may cause confusion for users regarding their current page.
**To Reproduce**
1.Navigate to the "places" page on the website.
2.Check the URL displayed in the browser.
3. See error

**Observed Behavior**
The URL shows "home" instead of "places."

**Expected behavior**
the URL should be https://tourism-peach.vercel.app/places

**Screenshots**
![issue5](https://github.com/Omkar-Sonawane-23/Tourism/assets/121476456/29c38dde-f661-4cc9-9216-33274bb83288)

**Desktop :**
 - OS: [windows]
 - Browser [ chrome, edge, Brave]

**Additional context**
I would like to fix this issue. Please assign it to me under GSSOC'24.

**Comment by sameer-soni** [comment]
@chandannekya assigned.
