### ISSUE TITLE
Places in the navbar not working

### ISSUE THREAD

**Issue by Rakshit-gen** [Omkar-Sonawane-23/Tourism#33]
**Describe the bug**
Can't navigate to places of visit using the link in navbar

**To Reproduce**
1. Go to the navbar
2. Click on the places
3. Nothing would show up

**Expected behavior**
It should have taken us to the places page.

**Additional context**
Please assign these issues to me. I am a contributor for GSSoC 2024.

**Comment by Omkar-Sonawane-23** [comment]
Duplicate!!
