### ISSUE TITLE
Feat/ui of faq section

### ISSUE THREAD

**Issue by drick-infinity** [Omkar-Sonawane-23/Tourism#337]
**Is your feature request related to a problem? Please describe.**
ui is not proper

**Describe the solution you'd like**
we can use better tailwind css for this property as well better colours are needed like as this theme we can use orange color 

**Describe alternatives you've considered**
use cards or box- shadows for better ui

**Comment by drick-infinity** [comment]
i work on this issue assign under gssoc'24

**Comment by sameer-soni** [comment]
@drick-infinity give it a try, if yours will be better then will merge it
