### ISSUE TITLE
Bug/ the plus symbol is not working on clicking in faq section

### ISSUE THREAD

**Issue by drick-infinity** [Omkar-Sonawane-23/Tourism#339]
**Describe the bug**
on clicking plus symbol in faq section in not working on clicking it works clicking the question
**To Reproduce**
1. Go to 'Faq section'
2. Click on '+'.
3. See error

**Comment by sameer-soni** [comment]
@drick-infinity would like to work on this?

**Comment by drick-infinity** [comment]
yes I worked on this issue under gssoc'24

**Comment by nishant0708** [comment]
can you assign me this issue.under gssoc24
