### ISSUE TITLE
[BUG] Login and register form bugs

### ISSUE THREAD

**Issue by Piyushk8** [Omkar-Sonawane-23/Tourism#345]
1) Input text not visible in REGISTER page
2)Password toggle button not working as expected

**Comment by sameer-soni** [comment]
@Piyushk8 would you like to work on this issue?

**Comment by VedaVarxha** [comment]
If this issue is not already assigned, I would like to work on this issue under GSSOC'24. Please assign it to me.

**Comment by Piyushk8** [comment]
> @Piyushk8 would you like to work on this issue?

YES , i would like to work on this issue please assign  me under GSSOC'24

**Comment by sameer-soni** [comment]
@Piyushk8 assigned.
