### ISSUE TITLE
Footer is not showing in every page

### ISSUE THREAD

**Issue by RamakrushnaBiswal** [Omkar-Sonawane-23/Tourism#390]
**Is your feature request related to a problem? Please describe.**
![image](https://github.com/Omkar-Sonawane-23/Tourism/assets/125277258/ea88164a-0753-42a4-9af4-a86ab49514bd)
in faq page and places page

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by RamakrushnaBiswal** [comment]
Hi @sameer-soni  assign it to me under GSSOC 24

**Comment by Dhevamuthu** [comment]
assign me this issue under GSSOC 2024
