### ISSUE TITLE
Redesign the login page and make it responsive

### ISSUE THREAD

**Issue by R1MO9** [Omkar-Sonawane-23/Tourism#421]
**Describe the bug**

**To Reproduce**
- Go to '/login'

**Desktop (please complete the following information):**
- redesign needed

**Smartphone (please complete the following information):**
- redesign needed

**Additional context**
Responsible

**Comment by R1MO9** [comment]
@helloworld-chhanda @Rakshit-gen @Disha-Hati @Arghyadeep09  assign me this issue

**Comment by Rakshit-gen** [comment]
@R1MO9 bro I'm not a PA stop tagging me

**Comment by R1MO9** [comment]
Resolved
