### ISSUE TITLE
Improving the UI of the Detailed section page and fixing the Overflowing

### ISSUE THREAD

**Issue by shubhammjha22** [Omkar-Sonawane-23/Tourism#43]
**Is your feature request related to a problem? Please describe.**
The Ui of the detailed section page isn't appealing and has Poor user experience, as some texts are not even readable
For example when going to the detailed section page of Goa

![Screenshot 2024-05-10 191221](https://github.com/Omkar-Sonawane-23/Tourism/assets/68507333/76aecf2f-2f57-4ebf-a643-ca3bc647f46a)

![image](https://github.com/Omkar-Sonawane-23/Tourism/assets/68507333/b54a9bf0-e542-4124-b064-b6b1b0152dd2)

**Describe the solution you'd like**
 I can implement a proper layout by giving it spacing and alignment on the page, improving the overall appearance. To enhance the design and ensure a more cohesive look, additionally the Page has a Horizontal Scroll due to Overflowing Content.  I can fix that

**Please Assign this issue to me under GSSoc'24 so that i can work on it**

**Comment by rishabh-bijalwan12** [comment]
Kindly assign me this issue under GSSOC'24

**Comment by DivyaNareshkumarPatel** [comment]
Is there a way for users to interact smoothly with the Detailed section page? Currently, the detail section overflows and lacks responsiveness, which affects user experience.

I propose enhancing the UI of the Detailed section page and ensuring its responsiveness across different screen sizes. This could involve optimizing layout and fixing overflowing issues for better usability.

Alternatives could involve minor adjustments within the existing layout, but a comprehensive improvement would provide a smoother user experience.

Please assign me this task. I'm a GSSOC '24 contributor eager to contribute.

**Comment by agxmbedi** [comment]
I am Agamjot singh. Under GSSOC'24, I would like to work on this issue. Pls assign me this!!

**Comment by shubhammjha22** [comment]
I would request you all to stop this unnecessary spams and Kindly first go through Guidelines of Opensource Contribution

**Comment by Omkar-Sonawane-23** [comment]
@shubhammjha22 You can start working on This.

**Comment by shubhammjha22** [comment]
Hey @Omkar-Sonawane-23,
I noticed that there's another issue (#54) addressing the same problem. It seems some changes have been made there. Before diving into this, could you take a look at the solution proposed in #54? If you find it satisfactory, we can consider closing this issue. Otherwise, I'm ready to start working on it.

**Comment by Omkar-Sonawane-23** [comment]
Thanks For Telling Us About This.They Completed The Issue. Unfortunately This issue is Duplicate. You can pickup Another Issue.
