### ISSUE TITLE
Explore Button

### ISSUE THREAD

**Issue by pani2004** [Omkar-Sonawane-23/Tourism#44]
The Explore button in the home page doesn't lead to anywhere.  I am contributor at the GSSOC'24 and i want to work on this issue, please assign me this problem.
![Screenshot (21)](https://github.com/Omkar-Sonawane-23/Tourism/assets/154724111/ae9b5b1b-3a4f-4637-80fd-b75c86f8d1b5)

**Comment by pani2004** [comment]
Hey @Omkar-Sonawane-23 can u please assign this issue to me. I am a GSSOC'24 contributor.

**Comment by Omkar-Sonawane-23** [comment]
What Content You Add In the Explore Section?

**Comment by Paarisha1** [comment]
can i contribute in this under gssoc

**Comment by pani2004** [comment]
@Omkar-Sonawane-23  In the pages folder a explore.jsx file is there in which two select tags are there having different options which are not being rendered, i can render it and if you want to add anything more in the explore section please provide it i can add it.
![Explore](https://github.com/Omkar-Sonawane-23/Tourism/assets/154724111/0e3e9438-9ac1-44b0-bf53-0901cc53e172)
![Home](https://github.com/Omkar-Sonawane-23/Tourism/assets/154724111/b1ba74e3-1aaa-47b7-8efa-ddcc1208553a)
I have added a link for routing in the home.jsx for the explore button and added some tailwind classes for the select tags in the explore.jsx.

**Comment by Omkar-Sonawane-23** [comment]
@pani2004 Can you add Filters In Explore Sections? E.X Historical Places, Thriller, Calmer

**Comment by pani2004** [comment]
@Omkar-Sonawane-23 Yes I can

**Comment by Mukesh-ghildiyal** [comment]
@Omkar-Sonawane-23  assign me this issue

**Comment by pani2004** [comment]
@Omkar-Sonawane-23 I have added 4 places for each category is that ok or do you want me to add more places?
![Screenshot (24)](https://github.com/Omkar-Sonawane-23/Tourism/assets/154724111/ccedd6af-dbd5-41b3-bf6b-a85bb10d2b3f)

**Comment by Omkar-Sonawane-23** [comment]
@pani2004 You can if You Want But For Now Its Enough.

**Comment by pani2004** [comment]
@Omkar-Sonawane-23  I have created a PR https://github.com/Omkar-Sonawane-23/Tourism/pull/159#issue-2291875678.Please check it
