### ISSUE TITLE
Page Responsiveness Issues on Different Screen Sizes

### ISSUE THREAD

**Issue by krishnas005** [Omkar-Sonawane-23/Tourism#48]
The current page layout does not respond effectively to different screen sizes, which leads to poor user experience on devices with varying resolutions, such as tablets and mobile phones. This lack of responsiveness can cause elements to overlap, become misaligned, or be displayed off-screen, making the content difficult to view and interact with.

![Screenshot 2024-05-10 222632](https://github.com/Omkar-Sonawane-23/Tourism/assets/117625683/60424e80-f080-49f5-bb78-c310790525fb)

**Comment by krishnas005** [comment]
@Omkar-Sonawane-23 I can fix this issue please assign this to me under GSSOC'24

**Comment by Omkar-Sonawane-23** [comment]
Duplicate

Issue : #23
