### ISSUE TITLE
add Night mode , navbar ui , animations

### ISSUE THREAD

**Issue by Shushant-Priyadarshi** [Omkar-Sonawane-23/Tourism#49]
the site deserves to have night mode , improved navbar UI and some animation on the cards .

**Comment by Shushant-Priyadarshi** [comment]
Assign this issue to me under gssoc24

**Comment by aasthax1** [comment]
Please assign this isuuse to me , I am sure i will make it look attractive with animation,night mode and navbar UI.Thank you

**Comment by Omkar-Sonawane-23** [comment]
Duplicate 

Issue : #31
