### ISSUE TITLE
on submit contact us nothing is happen adding backend functionality 

### ISSUE THREAD

**Issue by Isha1233** [Omkar-Sonawane-23/Tourism#491]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Isha1233** [comment]
@Omkar-Sonawane-23  kindly assign this issue to me

**Comment by riyasaxena32** [comment]
plz assign me this issue to make contribution to the project. under GSSOC
