### ISSUE TITLE
Documentation improvement

### ISSUE THREAD

**Issue by Shushant-Priyadarshi** [Omkar-Sonawane-23/Tourism#50]
The code is missing the script for running the program. npm start is not working

**Comment by Shushant-Priyadarshi** [comment]
Assign this issue to me under gssoc24

**Comment by Ayush-may** [comment]
@Shushant-Priyadarshi  u need to install it first use `npm install` this will install all the packages neeeded to run the program and in last run the program using `npm start` .

if u r trying to run the program without doing `npm install` then `npm start`  never going work
