### ISSUE TITLE
Adding a better hover effect and fixing the background on mobile view.

### ISSUE THREAD

**Issue by DHRUVKHANDELWAL00** [Omkar-Sonawane-23/Tourism#51]
**Is your feature request related to a problem? Please describe.**
Adding a better hover effect in explore page and fixing the background on mobile view.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by DHRUVKHANDELWAL00** [comment]
HEy @Omkar-Sonawane-23  please assign me under GSSOC

**Comment by Omkar-Sonawane-23** [comment]
Duplicate

**Comment by riyasaxena32** [comment]
please assign me .i can add hover effect

**Comment by Omkar-Sonawane-23** [comment]
Duplicate
