### ISSUE TITLE
adding about us page 

### ISSUE THREAD

**Issue by shubhdoshi21** [Omkar-Sonawane-23/Tourism#52]
I am a proud contributor to **GSSoC 2024**, where I have been actively involved in [mention specific contributions or projects]. I am passionate about open-source development and excited to be part of such a vibrant community. Looking forward to more opportunities to learn and contribute!

**Please assign this to me so that i can start working on it**

**Comment by aasthax1** [comment]
Please assign this to me. I am very much versed in Reactjs.
