### ISSUE TITLE
Improve Card Visibility, Content Readability and Fix Card Styling in 'Places' section

### ISSUE THREAD

**Issue by divyansh141** [Omkar-Sonawane-23/Tourism#55]
**Describe the bug**
In places section, content is not visible in Cards and I noticed some card UI is not properly visible. I have attached the screenshot.

**To Reproduce**
1. Click on 'Places' button on Home Page
2. See the Card UI

**Expected behavior**
Content of cards should be clearly visible and readable. Each card should have consistent UI stylings.

**Screenshots**
![image](https://github.com/Omkar-Sonawane-23/Tourism/assets/64478348/c0cc1aed-fd95-45d6-a31c-ba1838a7d3c2)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Version: Latest

I can fix it as soon as possible. Assign it to me under GSSOC'24.

**Comment by Omkar-Sonawane-23** [comment]
Duplicate
