### ISSUE TITLE
Navigating the PLACES link in the navbar as it is not functioning properly

### ISSUE THREAD

**Issue by anwesha2002** [Omkar-Sonawane-23/Tourism#57]
@Omkar-Sonawane-23 
In the navbar while clicking on the PLACES link it is not showing any results. But should show the places page but it is not linked properly. I am a gssoc'24 contributor . Can you assign me this issue

1. Go to https://tourism-peach.vercel.app/  link
2. Click on PLACES on navbar
3. See error

It should go to the places page but as it is not navigated properly it is now showing up any page.

![Screenshot 2024-05-10 151710](https://github.com/Omkar-Sonawane-23/Tourism/assets/116761608/05f4d00d-d1ed-4f46-bb67-11a0d44294c4)

**Desktop**
 - OS: windows
 - Browser : chrome
 - Version : latest

I would also like to make changes in some UI for detailed places page to make better user experience.

**Comment by Omkar-Sonawane-23** [comment]
Duplicate
