### ISSUE TITLE
Improvising readme.md file 

### ISSUE THREAD

**Issue by anwesha2002** [Omkar-Sonawane-23/Tourism#59]
@Omkar-Sonawane-23 
The readme.md file is not describing the project properly . I would like to improvise it.
I am a gssoc'24 contributor . can you please assign me this issue

I would like to add a clear description for the projects features with some added screen shots and will add the steps precisely to run the project in local machine for the user

**Comment by Omkar-Sonawane-23** [comment]
Duplicate
