### ISSUE TITLE
[BUG]: navbar place button not responding on a click

### ISSUE THREAD

**Issue by Ayush-may** [Omkar-Sonawane-23/Tourism#61]
**Describe the bug**
The place button isnt working ,there is not link 

**To Reproduce**
1. Open the site 
2. Click on the place button up in the navbar

**Expected behavior**
It should have changed the route but itnt changing

**Screenshots**

![image](https://github.com/Omkar-Sonawane-23/Tourism/assets/112775332/9057fff9-64c1-4ec7-b249-ed0675103100)

**Desktop (please complete the following information):**
 - OS: Ubunto
 - Browser: FireFox

**Additional Context**
There is not any hover effects in them

**Comment by Ayush-may** [comment]
assign me this issue

**Comment by Omkar-Sonawane-23** [comment]
Duplicate
