### ISSUE TITLE
[Bug] : Navigation bar layout missing

### ISSUE THREAD

**Issue by sivaprasath2004** [Omkar-Sonawane-23/Tourism#65]
**Describe the bug**
The navigation bar on mobile site `About us`  UI issue.

**To Reproduce**
1. Go to the page 
2. Click on  and inspect
3. Scroll down to `navigation bar`

**Expected behavior**
The `About us`  element can be `font-size` will decrease more UI accessable.

**Screenshots**
![Screenshot from 2024-05-11 07-59-14](https://github.com/Omkar-Sonawane-23/Tourism/assets/121082414/d48f65ef-a396-40b8-94e8-15f47617bd97)

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Browser : chrome

**Smartphone (please complete the following information):**
 - Device:Realme 8
 - OS: Android 12
 - Browser : chrome

**Comment by Ayush-may** [comment]
@sivaprasath2004  I have already solved the issue in #64 , this is **responsiveness issue not the font-size** 

Even though decreasing the font size is not a good way to fix this

**Comment by sivaprasath2004** [comment]
@Ayush-may  i will type the issue the #64 issue can be create 4min ago. sorry i will not notice that
