### ISSUE TITLE
Improve UI of Homeque.jsx (where places cards are shown)

### ISSUE THREAD

**Issue by KritikaBindal07** [Omkar-Sonawane-23/Tourism#68]
**Describe the bug**
UI of Homeque.jsx is not attractive and not responsive as well 

**To Reproduce**
1. Go to Home page
2. Click on Places button
3. See UI

**Comment by KritikaBindal07** [comment]
Hi @Omkar-Sonawane-23 , Can you Please assign me this issue. I'll improve it's UI and make it responsive.

**Comment by Omkar-Sonawane-23** [comment]
Duplicate.
