### ISSUE TITLE
Places cards UI can be improved and some images are not loading.

### ISSUE THREAD

**Issue by AtharvKasar04** [Omkar-Sonawane-23/Tourism#72]
**Describe the bug**

- Some images in the cards are not loading.
- UI of the cards can be improved as the text can be made at the top in every card.
- Additionally, Favicon i will be adding and the title of the web-page isnt related to the project.

**Screenshots**
![image](https://github.com/Omkar-Sonawane-23/Tourism/assets/108543702/a19faefc-bc48-4f73-a3f7-6e8738cc146f)
![image](https://github.com/Omkar-Sonawane-23/Tourism/assets/108543702/8976a87c-eb53-4a5d-91f6-704f4ae58b2e)

**Some cards have poor visibility of the texts so improving them.**

@Omkar-Sonawane-23 Can you assign this issue to me under GSSoC'24, I'm interested to work on this project.
I will relevant favicons and the mentioned UI changes.

Thank You!

**Comment by aditya7483thakur** [comment]
Hello Mentor ! can you assign this issue to me

**Comment by Omkar-Sonawane-23** [comment]
Duplicate
