### ISSUE TITLE
[BUG] - Navbar links are not working.

### ISSUE THREAD

**Issue by NilanchalaPanda** [Omkar-Sonawane-23/Tourism#75]
## Description
The navbar links are not working like About Us ad Places. Every link redirects again to home page only.

## Steps to Reproduce
1. Go to [Tourism website](https://tourism-peach.vercel.app/)
2. Click on About Us or Places
4. Page does not navigate to respective links.

## Screenshots
![image](https://github.com/Omkar-Sonawane-23/Tourism/assets/110488337/70633838-c0a5-4050-b345-3407a6f08a30)

**Desktop (please complete the following information):**

I would love to contribute and work upon the issue as a GSSoC'24 contributor. Looking forward for your reply.

**Comment by kamalesh-og** [comment]
Hi @NilanchalaPanda 
I am one of the contributors to GSSOC'24, and I would like to work on this issue "Navbar links are not working."
I have experience in Web Development and want to contribute to projects in open source, and have solved these kinds of issues prior, and ready to learn and make appropriate changes to enhance your project.
Can you please assign this issue to me?!
Thank You.

**Comment by NilanchalaPanda** [comment]
I also want to work on this issue as a GSS0C'24 contributor, you can raise any other issue and contribute to it. Happy Hacking!

**Comment by mohit-bhandari45** [comment]
I also want to work on this issue as a GSS0C'24 contributor

**Comment by Mohammad-Qamar** [comment]
Hello ,
I am one of the contributors to GSSOC'24, and I would like to work on this issue "Navbar links are not working."
I  think i can make appropriate changes to enhance your project.
Can you please assign this issue to me?!
Thank You.

**Comment by Omkar-Sonawane-23** [comment]
Solved In Dev Branch.
