### ISSUE TITLE
 Title: Navbar "Places" Button Not Functioning

### ISSUE THREAD

**Issue by SabanaSultana** [Omkar-Sonawane-23/Tourism#76]
**Describe the bug**
The "Places" button in the navbar is unresponsive; clicking on it does not result in any action or page opening.
When attempting to access information through the "Places" button in the navbar, users encounter a non-functional element. This issue prevents users from accessing relevant content related to different places of interest, hindering their ability to explore the website effectively.

**To Reproduce**
1. Go to 'https://tourism-peach.vercel.app/'
2. Click on  'Places button on the navbar'

**Expected behavior**
Clicking on the "Places" button in the navbar should trigger a response, either by opening a new page containing information about various places or by initiating another action that guides users to relevant content. The 'Places' button on the navbar should be linked with https://tourism-peach.vercel.app/home

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser : Chrome

**Comment by SabanaSultana** [comment]
@Omkar-Sonawane-23  Please assign me the issue so that I can start my work

**Comment by Omkar-Sonawane-23** [comment]
Solved This Issue in Dev branch.
