### ISSUE TITLE
Title: Incorrect route  name for Places page

### ISSUE THREAD

**Issue by SabanaSultana** [Omkar-Sonawane-23/Tourism#78]
**Describe the bug**
"When clicking on the 'Places' button, the route that opens is https://tourism-peach.vercel.app/home. I believe there should be a change in the route name."

**To Reproduce**
1. Go to 'https://tourism-peach.vercel.app/'
2. Click on the 'Places' button on the body'
3. See the path name

**Expected behavior**
"When clicking on the 'Places' button, the route name should be https://tourism-peach.vercel.app/places. This will prevent any confusion among users about the page."

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser :Chrome

**Comment by SabanaSultana** [comment]
@Omkar-Sonawane-23  Pls assign me the issue

**Comment by mohit-bhandari45** [comment]
@Omkar-Sonawane-23 Assign me under gssoc24
