### ISSUE TITLE
Adding a 404 Not Found page

### ISSUE THREAD

**Issue by Poushik11** [Omkar-Sonawane-23/Tourism#79]
**Is your feature request related to a problem? Please describe.**
Yes It will be suitable if the links not leading to any other pages
**Describe the solution you'd like**
If the Url is not valid we should be directed to 404 not found page
**Describe alternatives you've considered**

**Additional context**
please assign this issue to me i can make a good page and will help in interface too

**Comment by krishnas005** [comment]
@Omkar-Sonawane-23 I can fix this. Assign this issue to me under GSSOC'24.

**Comment by Poushik11** [comment]
I added the 404 Not Found page and created a PR #129 please review it
