### ISSUE TITLE
Place UI issue, image loading issue

### ISSUE THREAD

**Issue by Ankitapanda25** [Omkar-Sonawane-23/Tourism#83]
**Is your feature request related to a problem? Please describe.**
In the places page, a lot of place lack or there is a problem of image rendering.
The UI of the cards component can be made better as it is too frustrating to have a description placed on top of the images.

**Describe the solution you'd like**
Considering the UI for the card, the card can have a flip animation, when clicked.. the card flips and its description can be shown
The image rendering could be due to the non availability of images link currently which can be solved by actually creating an images folder and storing the images there.

**Additional context**
<img width="1067" alt="image" src="https://github.com/Omkar-Sonawane-23/Tourism/assets/123666302/583119e9-095a-4b6f-90ec-1555578b5b79">

@Omkar-Sonawane-23 Please assign me this under GSSOC'24 so that I can work on it and create a PR within a few hours

**Comment by Omkar-Sonawane-23** [comment]
Duplicate. Already completed in Dev branch.
