### ISSUE TITLE
buttons not working properly, well structured navbar and overall responsiveness of the site

### ISSUE THREAD

**Issue by Leorasaharia** [Omkar-Sonawane-23/Tourism#86]
**Is your feature request related to a problem? Please describe.**
The current state of the project lacks responsiveness and a cohesive navigation system, making it challenging for users to navigate and interact with the website effectively. Users may experience frustration due to difficulty in accessing different sections of the site and encountering non-functional elements like the Explore button.

**Describe the solution you'd like**
I would like to address these issues by implementing the following solutions:
1. Make the website responsive across various devices to ensure a seamless user experience.
2. Design a well-structured navbar with links to key sections such as About Us, Places, and Home for easy navigation.
**3. Fix the Explore button (not working) functionality to enable users to access additional features or content seamlessly, console showing (failed to load resources).**

**Describe alternatives you've considered**
An alternative solution could involve redesigning the layout to prioritize essential information and functionalities, ensuring a more intuitive user experience. Additionally, enhancing the visual design with a consistent color scheme and typography can improve readability and aesthetics.

**Additional context**
Screenshots or mockups illustrating the proposed changes can provide helpful context for understanding the desired improvements. Additionally, considering user feedback and usability testing can further inform the implementation of these enhancements.

**Comment by Omkar-Sonawane-23** [comment]
Duplicate.
