### ISSUE TITLE
fix: Navigation of places button in header

### ISSUE THREAD

**Issue by Disha-Hati** [Omkar-Sonawane-23/Tourism#9]
I found this.

**Describe the bug**
The places on the header don't navigate anywhere, but the Places button navigates to /home.

**Expected behavior**
On Clicking Places on the header, it goes to /home (shows same behavior as the button). 

Can you please assign this issue to me? I want to work on it.

**Comment by AlaynaShaheen** [comment]
I can resolve this issue please assign this to me

**Comment by AlaynaShaheen** [comment]
I have forked this repo and I can solve this issue. Please assign this to me.

**Comment by Omkar-Sonawane-23** [comment]
@Disha-Hati You can Work On This. Happy Coding!!

**Comment by helloworld-chhanda** [comment]
the issue has been fixed:
https://github.com/Omkar-Sonawane-23/Tourism/pull/13

**Comment by Disha-Hati** [comment]
> @Disha-Hati You can Work On This. Happy Coding!!

Thank you. I have created PR, can you please merge .
https://github.com/Omkar-Sonawane-23/Tourism/pull/17

**Comment by Omkar-Sonawane-23** [comment]
@helloworld-chhanda  Please make PR in Dev Branch

**Comment by GarimaSingh0109** [comment]
The navbar is not aligned and the buttons aren't responsive. kindly assign me this task under #gssoc'24

**Comment by Disha-Hati** [comment]
@Omkar-Sonawane-23 
I created PR to Dev Branch
Can you please merge my PR? https://github.com/Omkar-Sonawane-23/Tourism/pull/29

**Comment by Omkar-Sonawane-23** [comment]
Completed
