### ISSUE TITLE
About Us page not functional.

### ISSUE THREAD

**Issue by ChandelAnish** [Omkar-Sonawane-23/Tourism#97]
The About page on our platform is currently non-functional. Users are unable to access it, leading to a disruption in communication and transparency. This issue needs immediate attention to restore the functionality and ensure a seamless user experience.

I assure you that I will implement this perfectly using react, so you could assign me this issue.

I have already started the implementations.

![aboutus](https://github.com/Omkar-Sonawane-23/Tourism/assets/123861376/aeaabf2a-10ea-4c71-8273-6daa1c1e0516)

**Comment by ChandelAnish** [comment]
@Omkar-Sonawane-23 Assign me the above issue under GSSOC'24

**Comment by Omkar-Sonawane-23** [comment]
Duplicate
